/* Build-time tool: turns the vertices of a glTF/GLB model into a C table of
 * quantised points, so the screensaver stays a single self-contained file.
 *
 *   gltf2points <model.glb> <out.c> <max_points> <symbol> <height>
 *
 * Output: normalised so the figure stands with its feet at y = 0, centred in
 * x/z, <height> units tall, Y up. Points are int16 with scale
 * <symbol>_point_scale. Vertices are strided uniformly down to <max_points>. */
#define CGLTF_IMPLEMENTATION
#include "cgltf.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define OUT_RANGE  16.0f         /* int16 covers +-16 units (room for a 15 m giant) */

int main(int argc, char **argv) {
    if (argc < 6) { fprintf(stderr, "usage: gltf2points model.glb out.c max_points symbol height\n"); return 2; }
    const char *in = argv[1], *out = argv[2], *sym = argv[4];
    long max_points = strtol(argv[3], NULL, 10);
    float out_height = (float)atof(argv[5]);
    if (max_points < 100) max_points = 100;
    if (out_height <= 0.f) out_height = 1.8f;

    cgltf_options opt = {0};
    cgltf_data *data = NULL;
    if (cgltf_parse_file(&opt, in, &data) != cgltf_result_success) { fprintf(stderr, "cannot parse %s\n", in); return 1; }
    if (cgltf_load_buffers(&opt, data, in) != cgltf_result_success) { fprintf(stderr, "cannot load buffers of %s\n", in); return 1; }

    /* Count positions across all nodes' meshes (world transforms applied). */
    size_t total = 0;
    for (size_t n = 0; n < data->nodes_count; ++n) {
        cgltf_node *node = &data->nodes[n];
        if (!node->mesh) continue;
        for (size_t p = 0; p < node->mesh->primitives_count; ++p)
            for (size_t a = 0; a < node->mesh->primitives[p].attributes_count; ++a)
                if (node->mesh->primitives[p].attributes[a].type == cgltf_attribute_type_position)
                    total += node->mesh->primitives[p].attributes[a].data->count;
    }
    if (total == 0) { fprintf(stderr, "no positions in %s\n", in); return 1; }

    float *pts = malloc(total * 3 * sizeof(float));
    size_t np = 0;
    for (size_t n = 0; n < data->nodes_count; ++n) {
        cgltf_node *node = &data->nodes[n];
        if (!node->mesh) continue;
        float m[16];
        cgltf_node_transform_world(node, m);
        for (size_t p = 0; p < node->mesh->primitives_count; ++p)
            for (size_t a = 0; a < node->mesh->primitives[p].attributes_count; ++a) {
                cgltf_attribute *attr = &node->mesh->primitives[p].attributes[a];
                if (attr->type != cgltf_attribute_type_position) continue;
                for (size_t i = 0; i < attr->data->count; ++i) {
                    float v[3];
                    cgltf_accessor_read_float(attr->data, i, v, 3);
                    float *o = &pts[np * 3];
                    o[0] = m[0] * v[0] + m[4] * v[1] + m[8]  * v[2] + m[12];
                    o[1] = m[1] * v[0] + m[5] * v[1] + m[9]  * v[2] + m[13];
                    o[2] = m[2] * v[0] + m[6] * v[1] + m[10] * v[2] + m[14];
                    np++;
                }
            }
    }
    cgltf_free(data);

    float mn[3] = { 1e30f, 1e30f, 1e30f }, mx[3] = { -1e30f, -1e30f, -1e30f };
    for (size_t i = 0; i < np; ++i)
        for (int k = 0; k < 3; ++k) {
            if (pts[i * 3 + k] < mn[k]) mn[k] = pts[i * 3 + k];
            if (pts[i * 3 + k] > mx[k]) mx[k] = pts[i * 3 + k];
        }
    float height = mx[1] - mn[1];
    if (height <= 0.f) height = 1.f;
    float scale = out_height / height;
    float cx = 0.5f * (mn[0] + mx[0]), cz = 0.5f * (mn[2] + mx[2]);

    size_t stride = (np + (size_t)max_points - 1) / (size_t)max_points;
    if (stride < 1) stride = 1;
    size_t nout = (np + stride - 1) / stride;

    FILE *f = fopen(out, "w");
    if (!f) { fprintf(stderr, "cannot write %s\n", out); return 1; }
    fprintf(f, "/* Generated by tools/gltf2points.c from %s - do not edit. */\n", in);
    fprintf(f, "/* %zu source vertices, every %zu-th kept. Bounds after normalisation: */\n", np, stride);
    fprintf(f, "/* x %.3f..%.3f  y %.3f..%.3f  z %.3f..%.3f */\n",
            (mn[0] - cx) * scale, (mx[0] - cx) * scale, 0.f, height * scale,
            (mn[2] - cz) * scale, (mx[2] - cz) * scale);
    fprintf(f, "const int   %s_point_count = %zu;\n", sym, nout);
    fprintf(f, "const float %s_point_scale = %.9ff;\n", sym, OUT_RANGE / 32767.f);
    fprintf(f, "const short %s_points[%zu * 3] = {\n", sym, nout);
    size_t col = 0;
    for (size_t i = 0; i < np; i += stride) {
        float x = (pts[i * 3 + 0] - cx) * scale;
        float y = (pts[i * 3 + 1] - mn[1]) * scale;
        float z = (pts[i * 3 + 2] - cz) * scale;
        int q[3] = { (int)lrintf(x / OUT_RANGE * 32767.f), (int)lrintf(y / OUT_RANGE * 32767.f),
                     (int)lrintf(z / OUT_RANGE * 32767.f) };
        for (int k = 0; k < 3; ++k) { if (q[k] > 32767) q[k] = 32767; if (q[k] < -32767) q[k] = -32767; }
        fprintf(f, "%d,%d,%d,", q[0], q[1], q[2]);
        if (++col % 8 == 0) fputc('\n', f);
    }
    fprintf(f, "\n};\n");
    fclose(f);
    free(pts);
    fprintf(stderr, "gltf2points: %s: %zu -> %zu points, height %.2f -> %.2f\n", sym, np, nout, height, out_height);
    return 0;
}
