#include "render.h"
#include "gl_loader.h"
#include "platform.h"
#include "models.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_WRITE_NO_STDIO_FAILURE_CHECK
#include "stb_image_write.h"

/* Embedded GLSL (generated by cmake/embed.cmake). */
extern const char shader_wall_vert[], shader_wall_frag[], shader_floor_vert[],
    shader_floor_frag[], shader_post_vert[], shader_ghost_frag[],
    shader_blur_frag[], shader_blit_frag[], shader_debris_vert[],
    shader_city_vert[], shader_man_vert[], shader_glitch_frag[],
    shader_mask_vert[], shader_mask_frag[], shader_ember_vert[];

/* The figure's silhouette, in the plane of the wall. */
#define MASK_W 160
#define MASK_H 320

/* Signal loss thresholds along the corridor (camera distance from the wall). */
#define SPARKLE_Z0  900.f
#define DISTORT_Z0  970.f
#define TVOFF_Z     999.f
#define TVOFF_S     0.8f      /* collapse duration */

/* Distant city horizon, opposite the wall. The camera z is clamped to 20, so
 * this can never be reached and the wall never leaves view. */
#define CITY_Z        750.0f
#define CITY_SPACING  3.5f
#define CITY_ROW_STEP 5.5f
#define CITY_ROWS     17
#define CITY_HALF_X   1400.0f   /* generated strip; fades out long before its edge */
#define CITY_POINT    1.6f
#define CITY_SCALE    10.0f     /* geometry scale relative to the original design */
#define FAR_PLANE     2500.0f
/* Floor debris: coarse cells around the camera, ~45 % populated. */
#define DEBRIS_CELL   3.0f
#define DEBRIS_COLS   28
#define DEBRIS_ROWS   12
#define DEBRIS_Z0    -4.0f
/* The figures' points (generated from the GLB models, see models.h).
 * Their dots follow the wall's dot size (a fraction of it, since a figure
 * packs 40k points into ~2 m), clamped so they stay legible at any setting. */
#define MAN_POINT_MIN   0.008f
#define MAN_POINT_MAX   0.045f
#define MAN_POINT_RATIO 0.35f

/* Uploads each model's quantised points as a float VBO with its own VAO. */
static void build_models(Renderer *r) {
    r->model_count = bw_model_count < BW_MAX_MODELS ? bw_model_count : BW_MAX_MODELS;
    for (int m = 0; m < r->model_count; ++m) {
        const ModelInfo *info = &bw_models[m];
        int n = *info->count;
        float *v = malloc((size_t)n * 3 * sizeof(float));
        if (!v) { r->models[m].count = 0; continue; }
        for (int i = 0; i < n * 3; ++i) v[i] = info->points[i] * *info->scale;
        glGenVertexArrays(1, &r->models[m].vao);
        glGenBuffers(1, &r->models[m].vbo);
        glBindVertexArray(r->models[m].vao);
        glBindBuffer(GL_ARRAY_BUFFER, r->models[m].vbo);
        glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)n * 3 * sizeof(float), v, GL_STATIC_DRAW);
        glEnableVertexAttribArray(0);
        glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, (void *)0);
        free(v);
        r->models[m].count = n;
    }
    glBindVertexArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
}

static mat4 man_model(float x_rel, float y, float z, int yaw_octant);

static void build_mask_target(Renderer *r) {
    glGenTextures(1, &r->tex_mask);
    glBindTexture(GL_TEXTURE_2D, r->tex_mask);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_R8, MASK_W, MASK_H, 0, GL_RED, GL_UNSIGNED_BYTE, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glGenFramebuffers(1, &r->fbo_mask);
    glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_mask);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, r->tex_mask, 0);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
        plat_log("scar mask framebuffer incomplete");
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

/* Draws a figure's points flat into the mask, so the wall can tell which of
 * its own pixels the figure covered. Only redone when the figure changes. */
static void render_mask(Renderer *r, int model, int yaw) {
    if (r->mask_model == model && r->mask_yaw == yaw) return;
    r->mask_model = model;
    r->mask_yaw = yaw;
    float half_w = bw_model_radius(model) * 1.15f;
    float height = bw_model_height(model) * 1.05f;
    mat4 m = man_model(0.f, 0.f, 0.f, yaw);
    glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_mask);
    glViewport(0, 0, MASK_W, MASK_H);
    glDisable(GL_BLEND);
    glClearColor(0.f, 0.f, 0.f, 0.f);
    glClear(GL_COLOR_BUFFER_BIT);
    glUseProgram(r->prog_mask);
    glUniformMatrix4fv(glGetUniformLocation(r->prog_mask, "uModel"), 1, GL_FALSE, m.m);
    glUniform1f(glGetUniformLocation(r->prog_mask, "uHalfW"), half_w);
    glUniform1f(glGetUniformLocation(r->prog_mask, "uHeight"), height);
    glUniform1f(glGetUniformLocation(r->prog_mask, "uPointPx"), 3.f);
    glBindVertexArray(r->models[model].vao);
    glDrawArrays(GL_POINTS, 0, r->models[model].count);
    glBindVertexArray(r->vao);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

/* Model matrix for a figure: yaw about Y in 45-degree steps, then place. */
static mat4 man_model(float x_rel, float y, float z, int yaw_octant) {
    float a = yaw_octant * (BW_PI / 4.f);
    mat4 m = m4_identity();
    m.m[0] = cosf(a);  m.m[8]  = sinf(a);
    m.m[2] = -sinf(a); m.m[10] = cosf(a);
    m.m[12] = x_rel;   m.m[13] = y;   m.m[14] = z;
    return m;
}

/* One wall grid pass: `cols` columns of `spacing`, column 0 at world index
 * `cell_base`. `skip_half` > 0 leaves out the band around the camera that
 * another (finer) pass already covers. */
static void draw_wall_grid(Renderer *r, int cols, int rows, float spacing, long long cell_base,
                           double origin_x, float point_world, float skip_half,
                           float mirror, float alpha_mul) {
    float grid_x0 = (float)((double)cell_base * spacing - origin_x);
    glUniform1i(r->wu.cols, cols);
    glUniform1i(r->wu.cell_base, (int)(cell_base & 0x7FFFFFFF));
    glUniform1f(r->wu.spacing, spacing);
    glUniform1f(r->wu.grid_x0, grid_x0);
    glUniform1f(r->wu.point_world, point_world);
    glUniform1f(r->wu.skip_half, skip_half);
    glUniform1f(r->wu.mirror, mirror);
    glUniform1f(r->wu.alpha_mul, alpha_mul);
    glDrawArrays(GL_POINTS, 0, cols * rows);
    r->points_drawn += cols * rows;
}

/* World-scale constants. The wall lives in the x/y plane at z = 0. */
#define FADE_HEIGHT   3.5f    /* e-folding height of the upward fade (at the wall) */
#define WALL_HEIGHT   (16.f * FADE_HEIGHT)  /* geometry height: far above the visible glow */
#define FOG_DIST      200.0f  /* the wall is fully dark this far along it */
#define HALF_EXTENT   240.0f  /* half of the x range of the fine grid: beyond the fade */
#define LOD_RINGS     0       /* coarser rings not needed: darkness falls inside the fine grid */
#define FAR_HALF      (HALF_EXTENT * (1 << LOD_RINGS))
#define MAX_COLS      4800
#define MAX_ROWS      700
/* Pixel size is chosen outright, not as a fraction of anything: from a dot
 * that shows as about 2 x 2 screen pixels at the wall, up to a chunky panel
 * LED. Density then says how far apart those dots sit, measured in the dots
 * themselves: at 100 % they stand one smallest-dot gap apart, and every
 * percent below that opens another dot's width of space between them, so at
 * 0 % the gap is a hundred dots wide plus that same smallest dot. */
#define PIXEL_WORLD_MIN 0.02f
#define PIXEL_WORLD_MAX 0.30f

void camera_reset(Camera *c) {
    c->y = 1.6f;
    c->z = 9.0f;
    c->yaw = 0.f;
    c->pitch = 0.14f;
    c->fov_y = 60.f * BW_PI / 180.f;
}

float render_view_height(const Camera *cam) {
    /* Height of the wall covered by the frustum at the wall plane (approx.). */
    float h = 2.f * cam->z * tanf(cam->fov_y * 0.5f) + cam->y;
    return clampf(h, 2.f, WALL_HEIGHT);
}

float render_view_half_width(const Camera *cam, float aspect) {
    float half = cam->z * tanf(cam->fov_y * 0.5f) * aspect;
    return clampf(half * 1.1f + 1.f, 2.f, HALF_EXTENT * 0.8f);
}

/* ------------------------------------------------------------------------ */
static unsigned compile(GLenum type, const char *src, const char *name) {
    unsigned sh = glCreateShader(type);
    glShaderSource(sh, 1, &src, NULL);
    glCompileShader(sh);
    GLint ok = 0;
    glGetShaderiv(sh, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char log[2048];
        glGetShaderInfoLog(sh, sizeof log, NULL, log);
        plat_log("shader %s failed:\n%s", name, log);
        glDeleteShader(sh);
        return 0;
    }
    return sh;
}

static unsigned link_program(const char *vs, const char *fs, const char *name) {
    unsigned v = compile(GL_VERTEX_SHADER, vs, name);
    unsigned f = compile(GL_FRAGMENT_SHADER, fs, name);
    if (!v || !f) return 0;
    unsigned p = glCreateProgram();
    glAttachShader(p, v);
    glAttachShader(p, f);
    glLinkProgram(p);
    glDeleteShader(v);
    glDeleteShader(f);
    GLint ok = 0;
    glGetProgramiv(p, GL_LINK_STATUS, &ok);
    if (!ok) {
        char log[2048];
        glGetProgramInfoLog(p, sizeof log, NULL, log);
        plat_log("program %s failed to link:\n%s", name, log);
        glDeleteProgram(p);
        return 0;
    }
    return p;
}

#define U(prog, field, name) r->field = glGetUniformLocation(prog, name)

/* 16 procedural 8x8 glyphs with a katakana-like feel: a spine, a few bars,
 * scattered dots. Deterministic so the atlas is identical on every run. */
static void build_glyph_atlas(Renderer *r) {
    unsigned char px[8 * 128];
    memset(px, 0, sizeof px);
    rng_t rng = { 0x6A09E667u };
    for (int g = 0; g < 16; ++g) {
        int spine = 2 + (int)(rng_f(&rng) * 4);          /* vertical stroke */
        int top = rng_f(&rng) < 0.7f;                     /* top bar */
        int mid = (int)(rng_f(&rng) * 8);                 /* a middle bar row */
        for (int y = 0; y < 8; ++y)
            for (int x = 0; x < 8; ++x) {
                int on = 0;
                if (x == spine && y > 0 && y < 7) on = 1;
                if (top && y == 1 && x > 0 && x < 7) on = 1;
                if (y == mid && x > 1 && x < 6) on = rng_f(&rng) < 0.8f;
                if (!on && rng_f(&rng) < 0.13f && x > 0 && x < 7) on = 1;
                if (y == 0 || y == 7 || x == 0 || x == 7) on = 0; /* 1px margin */
                px[y * 128 + g * 8 + x] = on ? 255 : 0;
            }
    }
    glGenTextures(1, &r->glyph_tex);
    glBindTexture(GL_TEXTURE_2D, r->glyph_tex);
    glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RED, 128, 8, 0, GL_RED, GL_UNSIGNED_BYTE, px);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
}

int render_init(Renderer *r) {
    memset(r, 0, sizeof *r);
    r->prog_wall  = link_program(shader_wall_vert,  shader_wall_frag,  "wall");
    r->prog_floor = link_program(shader_floor_vert, shader_floor_frag, "floor");
    r->prog_ghost = link_program(shader_post_vert,  shader_ghost_frag, "ghost");
    r->prog_blur  = link_program(shader_post_vert,  shader_blur_frag,  "blur");
    r->prog_blit  = link_program(shader_post_vert,  shader_blit_frag,  "blit");
    r->prog_debris = link_program(shader_debris_vert, shader_wall_frag, "debris");
    r->prog_city   = link_program(shader_city_vert,   shader_wall_frag, "city");
    r->prog_man    = link_program(shader_man_vert,    shader_wall_frag, "man");
    r->prog_glitch = link_program(shader_post_vert,   shader_glitch_frag, "glitch");
    r->prog_mask   = link_program(shader_mask_vert,   shader_mask_frag, "mask");
    r->prog_ember  = link_program(shader_ember_vert,  shader_wall_frag, "ember");
    if (!r->prog_wall || !r->prog_floor || !r->prog_ghost || !r->prog_blur || !r->prog_blit ||
        !r->prog_debris || !r->prog_city || !r->prog_man || !r->prog_glitch || !r->prog_mask ||
        !r->prog_ember)
        return 0;
    build_mask_target(r);
    r->mask_model = -1;

    unsigned w = r->prog_wall;
    U(w, wu.view_proj, "uViewProj");   U(w, wu.cam_pos, "uCamPos");
    U(w, wu.cols, "uCols");            U(w, wu.spacing, "uSpacing");
    U(w, wu.cell_base, "uCellBase");
    U(w, wu.grid_x0, "uGridX0");       U(w, wu.point_world, "uPointWorld");
    U(w, wu.proj_scale, "uProjScale"); U(w, wu.max_point_px, "uMaxPointPx");
    U(w, wu.time, "uTime");            U(w, wu.wave_k, "uWaveK");
    U(w, wu.wave_amp, "uWaveAmp");     U(w, wu.wave_phase, "uWavePhase");
    U(w, wu.wave_phase2, "uWavePhase2");
    U(w, wu.fade_height, "uFadeHeight"); U(w, wu.fog_dist, "uFogDist");
    U(w, wu.mirror, "uMirror");        U(w, wu.alpha_mul, "uAlphaMul");
    U(w, wu.shimmer, "uShimmer");
    U(w, wu.spike_count, "uSpikeCount"); U(w, wu.spikes, "uSpikes");
    U(w, wu.pixel_type, "uPixelType"); U(w, wu.color, "uColor");
    U(w, wu.glyphs, "uGlyphs");        U(w, wu.surge, "uSurge");
    U(w, wu.skip_half, "uSkipHalf");   U(w, wu.wall_height, "uWallHeight");
    U(w, wu.scar_mask, "uScarMask");   U(w, wu.scar_rect, "uScarRect");
    U(w, wu.scar_state, "uScarState"); U(w, wu.scar_color, "uScarColor");

    unsigned f = r->prog_floor;
    U(f, fu.view_proj, "uViewProj");   U(f, fu.cam_x, "uCamX");
    U(f, fu.half_width, "uHalfWidth"); U(f, fu.z_near, "uZNear");
    U(f, fu.z_far, "uZFar");           U(f, fu.cam_pos, "uCamPos");
    U(f, fu.floor_color, "uFloorColor"); U(f, fu.space_color, "uSpaceColor");
    U(f, fu.wall_color, "uWallColor"); U(f, fu.fog_dist, "uFogDist");
    U(f, fu.wave_k, "uWaveK");         U(f, fu.wave_phase, "uWavePhase");
    U(f, fu.wave_amp, "uWaveAmp");

    r->ghost_cur   = glGetUniformLocation(r->prog_ghost, "uCurrent");
    r->ghost_prev  = glGetUniformLocation(r->prog_ghost, "uPrevious");
    r->ghost_decay = glGetUniformLocation(r->prog_ghost, "uDecay");
    r->blur_tex    = glGetUniformLocation(r->prog_blur, "uTex");
    r->blur_step   = glGetUniformLocation(r->prog_blur, "uStep");
    r->blit_tex    = glGetUniformLocation(r->prog_blit, "uTex");

    /* Core profile needs a VAO bound even with no attributes. */
    glGenVertexArrays(1, &r->vao);
    build_models(r);
    glBindVertexArray(r->vao);
    build_glyph_atlas(r);

    /* Some drivers reject this query in a core profile; fall back to 64 px. */
    while (glGetError() != GL_NO_ERROR) {}
    GLfloat range[2] = { 1.f, 64.f };
    glGetFloatv(GL_ALIASED_POINT_SIZE_RANGE, range);
    if (glGetError() != GL_NO_ERROR) range[1] = 64.f;
    r->max_point_px = range[1] < 8.f ? 8.f : (range[1] > 256.f ? 256.f : range[1]);

    glEnable(GL_PROGRAM_POINT_SIZE);
    glDisable(GL_DEPTH_TEST);
    glDisable(GL_CULL_FACE);
    plat_log("GL %s / %s, max point %.0f px", (const char *)glGetString(GL_RENDERER),
             (const char *)glGetString(GL_VERSION), r->max_point_px);
    gl_check("render_init");
    return 1;
}

/* ------------------------------------------------------------------------ */
static void make_target(unsigned *fbo, unsigned *tex, int w, int h) {
    if (!*tex) glGenTextures(1, tex);
    glBindTexture(GL_TEXTURE_2D, *tex);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    if (!*fbo) glGenFramebuffers(1, fbo);
    glBindFramebuffer(GL_FRAMEBUFFER, *fbo);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, *tex, 0);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
        plat_log("framebuffer incomplete (%dx%d)", w, h);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

static void ensure_targets(Renderer *r) {
    if (r->fbo_w == r->width && r->fbo_h == r->height && r->tex_scene) return;
    make_target(&r->fbo_scene, &r->tex_scene, r->width, r->height);
    make_target(&r->fbo_acc[0], &r->tex_acc[0], r->width, r->height);
    make_target(&r->fbo_acc[1], &r->tex_acc[1], r->width, r->height);
    make_target(&r->fbo_tmp, &r->tex_tmp, r->width, r->height);
    make_target(&r->fbo_out, &r->tex_out, r->width, r->height);
    r->fbo_w = r->width;
    r->fbo_h = r->height;
    r->acc_valid = 0;
}

void render_resize(Renderer *r, int w, int h) {
    r->width = w > 1 ? w : 1;
    r->height = h > 1 ? h : 1;
}

static void set_color(int loc, unsigned rgb) {
    glUniform3f(loc, ((rgb >> 16) & 255) / 255.f, ((rgb >> 8) & 255) / 255.f, (rgb & 255) / 255.f);
}

static void draw_fullscreen(void) { glDrawArrays(GL_TRIANGLES, 0, 3); }

/* ------------------------------------------------------------------------ */
void render_frame(Renderer *r, const Settings *s, const Sim *sim,
                  const Camera *cam, float time, float dt) {
    const float aspect = (float)r->width / (float)r->height;
    const int want_ghost = s->ghost_tail > 0;
    const int want_blur  = s->blur > 0;
    /* signal loss near the end of the corridor */
    float sparkle = clampf((cam->z - SPARKLE_Z0) / (DISTORT_Z0 - SPARKLE_Z0), 0.f, 1.f);
    float distort = clampf((cam->z - DISTORT_Z0) / (TVOFF_Z - DISTORT_Z0), 0.f, 1.f);
    float tv_target = cam->z >= TVOFF_Z ? 1.f : 0.f;
    r->tv_off = clampf(r->tv_off + (tv_target > r->tv_off ? 1.f : -1.f) * dt / TVOFF_S, 0.f, 1.f);
    const int glitch_on  = sparkle > 0.f || distort > 0.f || r->tv_off > 0.f;
    const int offscreen  = want_ghost || want_blur || glitch_on;

    /* --- grid parameters from the settings ------------------------------- */
    float point_world = PIXEL_WORLD_MIN *
        powf(PIXEL_WORLD_MAX / PIXEL_WORLD_MIN, s->pixel_size / 100.f);
    float gap = (100.f - (float)s->density) * point_world + PIXEL_WORLD_MIN;
    float spacing = point_world + gap;
    /* Depth level of detail: far from the wall the pixels would be many per
     * screen pixel and stack white-hot. Doubling the spacing for every
     * doubling of distance beyond 30 units keeps the on-screen density (and
     * the glow) the same as near the wall. Power-of-two steps keep cells
     * world-fixed between steps. The dots grow with it, so the wall keeps its
     * proportions and its brightness however far back the camera stands. */
    float depth_q = clampf(cam->z / 30.f, 1.f, 32.f);
    float depth_lod = powf(2.f, floorf(log2f(depth_q)));
    float point_world_base = point_world;
    spacing *= depth_lod;
    point_world *= depth_lod;
    /* Stepping back widens the view: the grid and the darkness fade scale
     * with distance so the wall never shows an end. Beyond FAR_BACK_Z the
     * wall looms: its glow height and its geometry grow with distance. */
    float half_extent = fmaxf(HALF_EXTENT, 1.6f * cam->z);
    float fog_dist = fmaxf(FOG_DIST, 1.5f * cam->z);
    float loom = 1.f + clampf((cam->z - FAR_BACK_Z) / 40.f, 0.f, 8.f);
    float fade_height = FADE_HEIGHT * loom;
    float wall_height = fmaxf(WALL_HEIGHT, 5.f * fade_height);
    int cols = (int)(2.f * half_extent / spacing) + 1;
    int rows = (int)(wall_height / spacing) + 1;
    if (cols > MAX_COLS) cols = MAX_COLS;
    if (rows > MAX_ROWS) rows = MAX_ROWS;
    /* When the column cap shortens the grid (high density near the wall),
     * darkness must still fall before the grid ends, or its ends show. */
    float actual_half = 0.5f * (float)(cols - 1) * spacing;
    if (fog_dist > actual_half * 0.95f) fog_dist = actual_half * 0.95f;
    /* Log scale: slider 0 gives pixels 1/100 of the spacing (about 2 screen
     * pixels at the default distance), slider 100 makes them touch. */
    float ratio = point_world / spacing;
    /* A small dot on a wide spacing lights only a little of the wall's area,
     * so at high density with small pixels the wall would go nearly black now
     * that the brightness is energy-correct. Individually brighten the dots as
     * they get sparser, the way a real panel keeps its output up. */
    float dot_comp = clampf(0.35f / fmaxf(ratio * ratio, 1e-4f), 1.f, 8.f);

    /* Everything on the GPU is relative to the simulation origin. */
    float cam_lx = (float)(cam->x - sim->origin_x);
    /* Grid columns sit on world multiples of the spacing, so pixels stay put
     * while the camera slides past them. The window of `cols` columns is
     * centred on the camera; its first world column index is `cell_base`,
     * which the shader uses to give every pixel a stable identity. */
    double base_k = floor(cam->x / spacing);
    long long cell_base = (long long)base_k - cols / 2;

    /* --- camera ------------------------------------------------------------ */
    vec3 eye = v3(cam_lx, cam->y, cam->z);
    vec3 dir = v3(sinf(cam->yaw) * cosf(cam->pitch), sinf(cam->pitch), -cosf(cam->yaw) * cosf(cam->pitch));
    mat4 view = m4_look_at(eye, v3_add(eye, dir), v3(0, 1, 0));
    mat4 proj = m4_perspective(cam->fov_y, aspect, 0.1f, FAR_PLANE);
    mat4 vp = m4_mul(proj, view);
    float proj_scale = r->height * 0.5f * proj.m[5];

    /* The imprint's silhouette, redrawn only when the figure changes. Must
     * come before the scene: it binds its own framebuffer and viewport. */
    int scar_mi = sim->ghost.scar_model;
    int has_scar = sim->ghost.scar_active && scar_mi >= 0 && scar_mi < r->model_count &&
                   r->models[scar_mi].count > 0;
    if (has_scar)
        render_mask(r, scar_mi, (settings_figure_yaw(s, scar_mi) + bw_models[scar_mi].base_yaw) & 7);

    /* --- scene ------------------------------------------------------------- */
    if (offscreen) {
        ensure_targets(r);
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_scene);
    } else {
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
    }
    glViewport(0, 0, r->width, r->height);
    glClearColor(((s->space_color >> 16) & 255) / 255.f, ((s->space_color >> 8) & 255) / 255.f,
                 (s->space_color & 255) / 255.f, 1.f);
    glClear(GL_COLOR_BUFFER_BIT);
    glBindVertexArray(r->vao);

    /* floor (opaque) */
    glDisable(GL_BLEND);
    glUseProgram(r->prog_floor);
    glUniformMatrix4fv(r->fu.view_proj, 1, GL_FALSE, vp.m);
    glUniform1f(r->fu.cam_x, cam_lx);
    glUniform1f(r->fu.half_width, FAR_HALF * 1.5f);
    glUniform1f(r->fu.z_near, cam->z + 900.f);   /* reaches under the city mirage */
    glUniform1f(r->fu.z_far, -30.f);
    glUniform3f(r->fu.cam_pos, eye.x, eye.y, eye.z);
    set_color(r->fu.floor_color, s->floor_color);
    set_color(r->fu.space_color, s->space_color);
    set_color(r->fu.wall_color, s->wall_color);
    glUniform1f(r->fu.fog_dist, fog_dist);
    glUniform1f(r->fu.wave_k, sim->wave_k);
    glUniform1f(r->fu.wave_phase, sim->wave_phase);
    glUniform1f(r->fu.wave_amp, sim->wave_amp);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

    glEnable(GL_BLEND);
    /* Glow is additive on a dark space color. On a light one (inverted
     * themes: white space, black wall) adding can only whiten, so the same
     * premultiplied output is composited "over" the background instead and
     * dark pixels darken it. */
    const float space_luma = (0.2126f * ((s->space_color >> 16) & 255) +
                              0.7152f * ((s->space_color >> 8) & 255) +
                              0.0722f * (s->space_color & 255)) / 255.f;
    const int light_bg = space_luma > 0.5f;
    glBlendFunc(GL_ONE, light_bg ? GL_ONE_MINUS_SRC_ALPHA : GL_ONE);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, r->glyph_tex);

    /* floor debris: a handful of pixels lying around so motion is felt */
    {
        unsigned p = r->prog_debris;
        long long dbase = (long long)floor(cam->x / DEBRIS_CELL) - DEBRIS_COLS / 2;
        /* rows follow the camera in z too (the corridor is deep), hashed on
         * the world row so debris stays put */
        int zbase = (int)floor(cam->z / DEBRIS_CELL) - DEBRIS_ROWS / 2;
        if (zbase < -2) zbase = -2;
        glUseProgram(p);
        glUniformMatrix4fv(glGetUniformLocation(p, "uViewProj"), 1, GL_FALSE, vp.m);
        glUniform3f(glGetUniformLocation(p, "uCamPos"), eye.x, eye.y, eye.z);
        glUniform1i(glGetUniformLocation(p, "uCols"), DEBRIS_COLS);
        glUniform1i(glGetUniformLocation(p, "uCellBase"), (int)(dbase & 0x7FFFFFFF));
        glUniform1i(glGetUniformLocation(p, "uZBase"), zbase);
        glUniform1f(glGetUniformLocation(p, "uCell"), DEBRIS_CELL);
        glUniform1f(glGetUniformLocation(p, "uX0"), (float)((double)dbase * DEBRIS_CELL - sim->origin_x));
        glUniform1f(glGetUniformLocation(p, "uZ0"), zbase * DEBRIS_CELL);
        glUniform1f(glGetUniformLocation(p, "uPointWorld"), fmaxf(point_world_base, 0.05f));
        glUniform1f(glGetUniformLocation(p, "uProjScale"), proj_scale);
        glUniform1f(glGetUniformLocation(p, "uMaxPointPx"), r->max_point_px);
        glUniform1f(glGetUniformLocation(p, "uTime"), time);
        glUniform1f(glGetUniformLocation(p, "uFogDist"), FOG_DIST * 0.6f);
        set_color(glGetUniformLocation(p, "uColor"), s->wall_color);
        glUniform1i(glGetUniformLocation(p, "uPixelType"), s->pixel_type);
        glUniform1i(glGetUniformLocation(p, "uGlyphs"), 0);
        glUniform1f(glGetUniformLocation(p, "uLightBg"), light_bg ? 1.f : 0.f);
        glDrawArrays(GL_POINTS, 0, DEBRIS_COLS * DEBRIS_ROWS);
    }

    /* distant city mirage behind the camera (upright + faint reflection) */
    if (s->horizon) {
        unsigned p = r->prog_city;
        int ccols = (int)(2.f * CITY_HALF_X / CITY_SPACING);
        long long cbase = (long long)floor(cam->x / CITY_SPACING) - ccols / 2;
        glUseProgram(p);
        glUniformMatrix4fv(glGetUniformLocation(p, "uViewProj"), 1, GL_FALSE, vp.m);
        glUniform1i(glGetUniformLocation(p, "uCols"), ccols);
        glUniform1i(glGetUniformLocation(p, "uCellBase"), (int)(cbase & 0x7FFFFFFF));
        glUniform1f(glGetUniformLocation(p, "uSpacing"), CITY_SPACING);
        glUniform1f(glGetUniformLocation(p, "uRowStep"), CITY_ROW_STEP);
        glUniform1f(glGetUniformLocation(p, "uX0"), (float)((double)cbase * CITY_SPACING - sim->origin_x));
        /* the mirage keeps its distance: it recedes as the camera steps back */
        glUniform1f(glGetUniformLocation(p, "uZ"), cam->z + CITY_Z);
        glUniform1f(glGetUniformLocation(p, "uScale"), CITY_SCALE);
        glUniform1f(glGetUniformLocation(p, "uCamX"), cam_lx);
        glUniform1f(glGetUniformLocation(p, "uHalfX"), CITY_HALF_X);
        glUniform1f(glGetUniformLocation(p, "uPointWorld"), CITY_POINT);
        glUniform1f(glGetUniformLocation(p, "uProjScale"), proj_scale);
        glUniform1f(glGetUniformLocation(p, "uMaxPointPx"), r->max_point_px);
        glUniform1f(glGetUniformLocation(p, "uTime"), time);
        set_color(glGetUniformLocation(p, "uColor"), s->horizon_color);
        glUniform1i(glGetUniformLocation(p, "uPixelType"), PIXEL_ROUND);
        glUniform1i(glGetUniformLocation(p, "uGlyphs"), 0);
        glUniform1f(glGetUniformLocation(p, "uLightBg"), light_bg ? 1.f : 0.f);
        int mirror_loc = glGetUniformLocation(p, "uMirror");
        glUniform1f(mirror_loc, -1.f);
        glDrawArrays(GL_POINTS, 0, ccols * CITY_ROWS);
        glUniform1f(mirror_loc, 1.f);
        glDrawArrays(GL_POINTS, 0, ccols * CITY_ROWS);
    }

    /* wall reflection, then the wall itself (additive glow) */
    glUseProgram(r->prog_wall);
    glUniform4f(r->wu.surge, (float)(sim->ghost.x - sim->origin_x), sim->ghost.reach,
                sim->ghost.width, time * 1.2f);
    /* the ghost's imprint: the wall colours the pixels the figure touched */
    glUniform1i(r->wu.scar_mask, 1);
    if (has_scar) {
        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, r->tex_mask);
        glActiveTexture(GL_TEXTURE0);
        glUniform4f(r->wu.scar_rect, (float)(sim->ghost.scar_x - sim->origin_x),
                    bw_model_radius(scar_mi) * 1.15f, bw_model_height(scar_mi) * 1.05f,
                    sim->ghost.z);
        glUniform2f(r->wu.scar_state, sim->ghost.scar_intensity, sim->ghost.scar_birth);
        set_color(r->wu.scar_color, bw_models[scar_mi].color);
    } else {
        glUniform4f(r->wu.scar_rect, 0.f, 1.f, 0.f, 0.f);   /* height 0: no imprint */
    }
    glUniformMatrix4fv(r->wu.view_proj, 1, GL_FALSE, vp.m);
    glUniform3f(r->wu.cam_pos, eye.x, eye.y, eye.z);
    glUniform1f(r->wu.proj_scale, proj_scale);
    glUniform2f(glGetUniformLocation(r->prog_wall, "uViewport"), (float)r->width, (float)r->height);
    glUniform1f(r->wu.max_point_px, r->max_point_px);
    glUniform1f(r->wu.time, time);
    glUniform1f(r->wu.wave_k, sim->wave_k);
    glUniform1f(r->wu.wave_amp, sim->wave_amp);
    glUniform1f(r->wu.wave_phase, sim->wave_phase);
    glUniform1f(r->wu.wave_phase2, sim->wave_phase2);
    glUniform1f(r->wu.fade_height, fade_height);
    glUniform1f(r->wu.wall_height, rows * spacing);   /* the actual generated top */
    glUniform1f(r->wu.fog_dist, fog_dist);
    glUniform1f(r->wu.shimmer, s->shimmer / 100.f);
    glUniform1f(glGetUniformLocation(r->prog_wall, "uDotComp"), dot_comp);
    glUniform1i(r->wu.spike_count, sim->gpu_spike_count);
    if (sim->gpu_spike_count > 0)
        glUniform4fv(r->wu.spikes, sim->gpu_spike_count, sim->gpu_spikes);
    glUniform1i(r->wu.pixel_type, s->pixel_type);
    glUniform1f(glGetUniformLocation(r->prog_wall, "uLightBg"), light_bg ? 1.f : 0.f);
    set_color(r->wu.color, s->wall_color);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, r->glyph_tex);
    glUniform1i(r->wu.glyphs, 0);

    /* Levels of detail: the fine grid near the camera, then rings that double
     * the spacing and the extent each time (40-80, 80-160, 160-320 units),
     * each skipping the band the previous level covers. A doubling step is
     * invisible at those distances, unlike one big coarse grid. Coarser
     * spacing means fewer points per area, so each ring is brightened to keep
     * the glow continuous. Everything is drawn twice: reflection, then wall. */
    r->points_drawn = 0;
    for (int pass = 0; pass < 2; ++pass) {
        float mirror = pass == 0 ? -1.f : 1.f;
        float base_alpha = pass == 0 ? 0.22f : 0.9f;
        float near_extent = HALF_EXTENT;
        /* the near grid may be narrower than HALF_EXTENT when capped */
        float near_actual = 0.5f * cols * spacing;
        if (near_actual < near_extent) near_extent = near_actual;
        for (int k = LOD_RINGS; k >= 1; --k) {
            float sp = spacing * (float)(1 << k);
            float ext = HALF_EXTENT * (float)(1 << k);
            int ccols = (int)(2.f * ext / sp) + 1;
            int crows = (int)(WALL_HEIGHT / sp) + 1;
            if (crows > MAX_ROWS) crows = MAX_ROWS;
            long long cb = (long long)floor(cam->x / sp) - ccols / 2;
            float inner = (k == 1) ? near_extent - sp : HALF_EXTENT * (float)(1 << (k - 1)) - sp;
            float comp = powf(2.f, 0.8f * (float)k);
            draw_wall_grid(r, ccols, crows, sp, cb, sim->origin_x,
                           point_world * (float)(1 << k), inner, mirror, base_alpha * comp);
        }
        draw_wall_grid(r, cols, rows, spacing, cell_base, sim->origin_x,
                       point_world, 0.f, mirror, base_alpha);
    }

    /* the figure, standing a few units from the wall (its imprint is not drawn
     * here: the wall colours its own pixels, see the scar uniforms above) */
    {
        const Ghost *g = &sim->ghost;
        int mi = g->model;
        if (mi < 0 || mi >= r->model_count || r->models[mi].count == 0 || g->alpha <= 0.001f)
            goto figure_done;
        unsigned p = r->prog_man;
        mat4 model = man_model((float)(g->x - sim->origin_x), bw_models[mi].elevation, g->z,
                               (settings_figure_yaw(s, mi) + bw_models[mi].base_yaw) & 7);
        glUseProgram(p);
        glUniformMatrix4fv(glGetUniformLocation(p, "uViewProj"), 1, GL_FALSE, vp.m);
        glUniformMatrix4fv(glGetUniformLocation(p, "uModel"), 1, GL_FALSE, model.m);
        /* the same number of points spread over a taller figure: brighten */
        float size_comp = clampf(bw_model_height(mi) / 1.8f, 1.f, 8.f);
        glUniform1f(glGetUniformLocation(p, "uAlpha"), g->alpha * size_comp);
        float man_point = clampf(point_world * MAN_POINT_RATIO, MAN_POINT_MIN, MAN_POINT_MAX);
        glUniform1f(glGetUniformLocation(p, "uTime"), time);
        glUniform1f(glGetUniformLocation(p, "uPointWorld"), man_point);
        glUniform1f(glGetUniformLocation(p, "uProjScale"), proj_scale);
        glUniform1f(glGetUniformLocation(p, "uMaxPointPx"), r->max_point_px);
        set_color(glGetUniformLocation(p, "uColor"), bw_models[mi].color);
        /* same dot shape as the wall, and the blur slider softens them the
         * same way: wider, dimmer sprites on top of the screen-space blur */
        glUniform1i(glGetUniformLocation(p, "uPixelType"), s->pixel_type);
        glUniform1f(glGetUniformLocation(p, "uSoften"), s->blur / 100.f);
        glUniform1i(glGetUniformLocation(p, "uGlyphs"), 0);
        glUniform1f(glGetUniformLocation(p, "uLightBg"), light_bg ? 1.f : 0.f);
        /* the dust clock, and the wave shape it is blown by */
        glUniform1f(glGetUniformLocation(p, "uWaveT"), g->wave_t);
        glUniform1f(glGetUniformLocation(p, "uWaveStart"), g->wave_start);
        glUniform1f(glGetUniformLocation(p, "uCrash"), g->crash);
        glUniform1f(glGetUniformLocation(p, "uWaveS"), g->wave_s);
        glUniform1f(glGetUniformLocation(p, "uDustVisible"), r->viewer_inside ? 1.f : 0.f);
        glUniform1f(glGetUniformLocation(p, "uWaveK"), sim->wave_k);
        glUniform1f(glGetUniformLocation(p, "uWaveAmp"), sim->wave_amp);
        glUniform1f(glGetUniformLocation(p, "uWavePhase"), sim->wave_phase);
        glUniform1f(glGetUniformLocation(p, "uWavePhase2"), sim->wave_phase2);
        glUniform4f(glGetUniformLocation(p, "uSurge"), (float)(g->x - sim->origin_x), g->reach,
                    g->width, time * 1.2f);
        glBindVertexArray(r->models[mi].vao);
        glDrawArrays(GL_POINTS, 0, r->models[mi].count);
        glBindVertexArray(r->vao);
    }
figure_done:
    /* the last sparks where a figure stood */
    if (sim->ghost.ember_t >= 0.f) {
        const Ghost *g = &sim->ghost;
        int mi = g->ember_model >= 0 && g->ember_model < r->model_count ? g->ember_model : 0;
        unsigned p = r->prog_ember;
        glUseProgram(p);
        glUniformMatrix4fv(glGetUniformLocation(p, "uViewProj"), 1, GL_FALSE, vp.m);
        glUniform1f(glGetUniformLocation(p, "uT"), g->ember_t);
        glUniform3f(glGetUniformLocation(p, "uPos"), (float)(g->ember_x - sim->origin_x), 0.f, g->ember_z);
        glUniform1f(glGetUniformLocation(p, "uHeight"), g->ember_h);
        glUniform1f(glGetUniformLocation(p, "uPointWorld"), 0.02f);   /* tiny */
        glUniform1f(glGetUniformLocation(p, "uProjScale"), proj_scale);
        glUniform1f(glGetUniformLocation(p, "uMaxPointPx"), r->max_point_px);
        glUniform1f(glGetUniformLocation(p, "uAlpha"), 0.85f);
        /* Sparks have to stand against the void they hang in: the figure's
         * own colour over a dark space, the (dark) wall colour over a light
         * one, where a bright spark would simply vanish. */
        set_color(glGetUniformLocation(p, "uColor"),
                  light_bg ? s->wall_color : bw_models[mi].color);
        glUniform1i(glGetUniformLocation(p, "uPixelType"), s->pixel_type);
        glUniform1i(glGetUniformLocation(p, "uGlyphs"), 0);
        glUniform1f(glGetUniformLocation(p, "uLightBg"), light_bg ? 1.f : 0.f);
        glDrawArrays(GL_POINTS, 0, EMBER_COUNT);
    }
    glDisable(GL_BLEND);

    if (!offscreen) return;
    /* where the finished picture goes: the screen, or the glitch pass input */
    const unsigned out_fbo = glitch_on ? r->fbo_out : 0;

    /* --- post: ghost tails --------------------------------------------------- */
    unsigned src_tex = r->tex_scene;
    if (want_ghost) {
        float base = r->ghost_decay_override > 0.f ? r->ghost_decay_override
                                                   : lerpf(0.80f, 0.975f, s->ghost_tail / 100.f);
        float decay = powf(base, dt * 60.f);          /* normalised to 60 Hz */
        int cur = r->acc_index, prev = cur ^ 1;
        if (!r->acc_valid) { decay = 0.f; r->acc_valid = 1; }
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_acc[cur]);
        glUseProgram(r->prog_ghost);
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, r->tex_scene);
        glUniform1i(r->ghost_cur, 0);
        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, r->tex_acc[prev]);
        glUniform1i(r->ghost_prev, 1);
        glUniform1f(r->ghost_decay, decay);
        glUniform1f(glGetUniformLocation(r->prog_ghost, "uInvert"), light_bg ? 1.f : 0.f);
        draw_fullscreen();
        glActiveTexture(GL_TEXTURE0);
        src_tex = r->tex_acc[cur];
        r->acc_index = prev;
    }

    /* --- post: blur ----------------------------------------------------------- */
    if (want_blur) {
        float radius = (s->blur / 100.f) * 7.f * ((float)r->height / 1080.f);
        if (radius < 0.5f) radius = 0.5f;
        glUseProgram(r->prog_blur);
        glUniform1i(r->blur_tex, 0);
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_tmp);
        glBindTexture(GL_TEXTURE_2D, src_tex);
        glUniform2f(r->blur_step, radius / 4.f / (float)r->width, 0.f);
        draw_fullscreen();
        glBindFramebuffer(GL_FRAMEBUFFER, out_fbo);
        glBindTexture(GL_TEXTURE_2D, r->tex_tmp);
        glUniform2f(r->blur_step, 0.f, radius / 4.f / (float)r->height);
        draw_fullscreen();
    } else {
        glBindFramebuffer(GL_FRAMEBUFFER, out_fbo);
        glUseProgram(r->prog_blit);
        glBindTexture(GL_TEXTURE_2D, src_tex);
        glUniform1i(r->blit_tex, 0);
        draw_fullscreen();
    }

    /* --- post: signal loss at the corridor's end ------------------------------ */
    if (glitch_on) {
        unsigned p = r->prog_glitch;
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        glUseProgram(p);
        glBindTexture(GL_TEXTURE_2D, r->tex_out);
        glUniform1i(glGetUniformLocation(p, "uTex"), 0);
        glUniform2f(glGetUniformLocation(p, "uResolution"), (float)r->width, (float)r->height);
        glUniform1f(glGetUniformLocation(p, "uTime"), time);
        glUniform1f(glGetUniformLocation(p, "uSparkle"), sparkle);
        glUniform1f(glGetUniformLocation(p, "uDistort"), distort);
        glUniform1f(glGetUniformLocation(p, "uTvOff"), r->tv_off);
        set_color(glGetUniformLocation(p, "uWallColor"), s->wall_color);
        set_color(glGetUniformLocation(p, "uCityColor"), s->horizon_color);
        set_color(glGetUniformLocation(p, "uSpaceColor"), s->space_color);
        draw_fullscreen();
    }
#ifdef BW_DEBUG
    gl_check("render_frame");
#endif
}

void render_shutdown(Renderer *r) {
    if (r->prog_wall) glDeleteProgram(r->prog_wall);
    if (r->prog_floor) glDeleteProgram(r->prog_floor);
    if (r->prog_ghost) glDeleteProgram(r->prog_ghost);
    if (r->prog_blur) glDeleteProgram(r->prog_blur);
    if (r->prog_blit) glDeleteProgram(r->prog_blit);
    if (r->prog_debris) glDeleteProgram(r->prog_debris);
    if (r->prog_city) glDeleteProgram(r->prog_city);
    if (r->prog_man) glDeleteProgram(r->prog_man);
    for (int m = 0; m < r->model_count; ++m) {
        if (r->models[m].vao) glDeleteVertexArrays(1, &r->models[m].vao);
        if (r->models[m].vbo) glDeleteBuffers(1, &r->models[m].vbo);
    }
    if (r->vao) glDeleteVertexArrays(1, &r->vao);
    if (r->glyph_tex) glDeleteTextures(1, &r->glyph_tex);
    if (r->prog_glitch) glDeleteProgram(r->prog_glitch);
    if (r->prog_mask) glDeleteProgram(r->prog_mask);
    if (r->prog_ember) glDeleteProgram(r->prog_ember);
    if (r->tex_mask) glDeleteTextures(1, &r->tex_mask);
    if (r->fbo_mask) glDeleteFramebuffers(1, &r->fbo_mask);
    unsigned texs[5] = { r->tex_scene, r->tex_acc[0], r->tex_acc[1], r->tex_tmp, r->tex_out };
    unsigned fbos[5] = { r->fbo_scene, r->fbo_acc[0], r->fbo_acc[1], r->fbo_tmp, r->fbo_out };
    glDeleteTextures(5, texs);
    glDeleteFramebuffers(5, fbos);
    memset(r, 0, sizeof *r);
}

int render_dump_png(const Renderer *r, const char *path) {
    int w = r->width, h = r->height;
    unsigned char *px = malloc((size_t)w * h * 4);
    if (!px) return 0;
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, px);
    /* OpenGL rows start at the bottom; PNG rows at the top. */
    for (int y = 0; y < h / 2; ++y) {
        unsigned char *a = px + (size_t)y * w * 4, *b = px + (size_t)(h - 1 - y) * w * 4;
        for (int i = 0; i < w * 4; ++i) { unsigned char t = a[i]; a[i] = b[i]; b[i] = t; }
    }
    for (size_t i = 3; i < (size_t)w * h * 4; i += 4) px[i] = 255;
    int ok = stbi_write_png(path, w, h, 4, px, w * 4);
    free(px);
    return ok;
}
