# Converts text files into C byte arrays. Invoked in script mode:
#   cmake -DOUT=<file.c> -DINPUTS=<a.glsl;b.glsl> -P embed.cmake
# Each input "wall.vert" becomes `const char shader_wall_vert[]` (NUL-terminated).
set(content "/* Generated by cmake/embed.cmake - do not edit. */\n")
foreach(f ${INPUTS})
  get_filename_component(name "${f}" NAME)
  string(MAKE_C_IDENTIFIER "shader_${name}" ident)
  file(READ "${f}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(APPEND content "const char ${ident}[] = { ${bytes} 0x00 };\n")
endforeach()
file(WRITE "${OUT}.tmp" "${content}")
configure_file("${OUT}.tmp" "${OUT}" COPYONLY)
file(REMOVE "${OUT}.tmp")
